version: '3.7'

services:
  tracebeef-postgres:
    container_name: tracebeef-postgres
    image: postgres:12.8-alpine
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PGDATA=/data/db
      - PGTZ=GMT
    expose:
      - 5432
    volumes:
      - /data/postgres/${APP_NAME}:/data/db/:z

  redis:
    container_name: qso_redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - .:/usr/app
    networks:
      - app-network
  # app:
  #   build:
  #     context: .
  #   container_name: app-all-module
  #   command: yarn start:dev
  #   ports:
  #     - '3002:3002'
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - app-network
  #   depends_on:
  #     - postgres
  #     - mongodb_container
  #     - redis

  # app-credit:
  #   build:
  #     context: .
  #   container_name: app-credit
  #   command: yarn credit:start:dev
  #   ports:
  #     - '3003:3003'
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - app-network

networks:
  app-network: